#!/usr/bin/php
<?php
/**
 * Description goes here...
 *
 * @author Pontus Östlund <spam@poppa.se>
*/

define('__SELF__', dirname(__FILE__));
define('__KEEP__', "/\.php$/");

require_once "plibcli.php";

PLib::Import('IO.StdIO');
PLib::Import('IO.StreamReader');

$opts = new Getoptlong('c|--classes');

$cls = $opts->Get('c') or exit("Missing required argument \"c\"!\n");
$cls = array_map('trim', explode(',', $cls));

index();

function index()
{
	$iter = Dir::RecursiveIterator(__SELF__);
	$cut = strlen(__SELF__)+1;

	foreach ($iter as $path => $file) {
		$rp = substr($file, $cut);
		if (!preg_match(__KEEP__, $rp) || strstr($rp, '/stx/'))
			continue;

		cwrite("$rp");
		$idx = new Index($rp);
	}
}

class Index
{
	public $path;
	public $classes = array();
	public $includes = array();
	
	public function __construct($path)
	{
		$this->path = $path;
		$this->parse();
	}
	
	private function parse()
	{
		$sr = new StreamReader($this->path);
		
		while (false !== ($line = $sr->ReadLine())) {
			
		}
		
		$sr->Close();
	}
}
?>
